spring:
  profiles: dev
# RDS - MySQL
  datasource:
    url: jdbc:mysql://mindup-rds.c9v1roxnwdza.ap-northeast-2.rds.amazonaws.com/mindup_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 2db8ddasf!
  # JPA setting
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  # thymeleaf PUT, DELETE Method use
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#S3
cloud:
  aws:
    credentials:
      instanceProfile: true
      accessKey: AKIA4TLFWIUBMEOUNEM5
      secretKey: 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
    s3:
      bucket: mindup-dev
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false